# Generated by Django 3.2.8 on 2021-10-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_itemlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='category_id',
            new_name='category',
        ),
    ]
