# Generated by Django 3.2.8 on 2021-10-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211020_1049'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlog',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
