# Generated by Django 3.2.8 on 2021-10-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_itemlog_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemLog',
        ),
    ]
